version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: cinema_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: cinema_app
    restart: always
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn cinema_service.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
  static_data:
  media_data:
